### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jaanos** [qwer317/opbprojekt#1]
Na vašem ER diagramu manjkajo omejitve tipa "največ en", torej puščice v relacije. Če ima npr. avto natanko eno znamko, naj bo puščica iz entitete `AVTO` v relacijo z entiteto `ZNAMKA`.

Poleg tega izgleda, da je entiteta `OCENA` nepotrebna - glede na to, da gre samo za število zvezdic, je to lahko kar atribut.

**Comment by qwer317** [comment]
Sedaj imamo že drug diagram.

**Comment by jaanos** [comment]
Nimam pripomb - edino pri pogonu najbrž želite za glavni ključ tip, ne opis (če prav razumem).
